### ISSUE TITLE
Highlight on "Like" and "Unlike" missing

### ISSUE THREAD

**Issue by Jan-Ka** [XDRosenheim/ChromeExtension#1]
Currently you don't see if you placed a "Like" or "Unlike" on a Video - the Color stays the same - should switch to a dimmed blue and red accordingly.

![dark_youtube_missing_accent](https://cloud.githubusercontent.com/assets/11042838/19199034/5e9079a6-8cc2-11e6-8631-d0b17ee2180e.JPG)
This Video is liked but the status is not visible

**Comment by XDRosenheim** [comment]
Has been added to the git: https://github.com/XDRosenheim/ChromeExtension/blob/master/styles.css#L84
But I haven't made a publish or an update for it... Will do it now.

**Comment by XDRosenheim** [comment]
##Version 1.1.1.
Extension update on Chrome store.
Uploaded an publish here on GitHub.
