### ISSUE TITLE
Subscriptions / Grid / Uploader Name wrong color

### ISSUE THREAD

**Issue by Jan-Ka** [XDRosenheim/ChromeExtension#2]
Seems to have to do with a change to how the "verified" Symbol is shown

![image](https://cloud.githubusercontent.com/assets/11042838/21150101/2bc20456-c15e-11e6-82db-fc131d4aacba.png)

**Comment by XDRosenheim** [comment]
It had nothing to do with the verified symbol, it was for all videos. (On my end at least.)

Uploading changes to Chrome Store...
A package should be available here on GitHub in a few minutes.

**Comment by XDRosenheim** [comment]
Chrome Store updated
